package net.timeless.animationapi;

import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.timeless.animationapi.client.CommandForceAnimation;

@Mod(modid = AnimationAPI.MODID, name = AnimationAPI.MODNAME, version = AnimationAPI.MODVERSION)
public class AnimationAPI
{
    public static final String MODID = "jcanimationapi";
    public static final String MODNAME = "JurassiCraft AnimationAPI";
    public static final String MODVERSION = "1.2.5";
    public static final String MODDESCRIPTION = "This is a required mod that supports the mob animations in JurassiCraft2.";
    public static final String MODAUTHOR = "TeamJC";
    public static final String MODCREDITS = "";
    public static final String MODURL = "https://jurassicraft.net/";
    // public static final String MODLOGO = "logo.png";

    @Mod.EventHandler
    public void serverLoad(FMLServerStartingEvent event)
    {
        event.registerServerCommand(new CommandForceAnimation());
    }
    
    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) 
    {       
        // hard-code mod information so don't need mcmod.info file
        event.getModMetadata().autogenerated = false ; // stops it from complaining about missing mcmod.info
        event.getModMetadata().credits = EnumChatFormatting.BLUE+MODCREDITS;
        event.getModMetadata().authorList.add(EnumChatFormatting.RED+MODAUTHOR);
        event.getModMetadata().description = MODDESCRIPTION;
        event.getModMetadata().url = MODURL;
        // event.getModMetadata().logoFile = MODLOGO;
    }

}
